on:
    release:
        types:
            - published

jobs:
    build:
        timeout-minutes: 60
        permissions:
            contents: write
        runs-on: ubuntu-22.04
        steps:
            - name: メインブランチをチェックアウト
              uses: actions/checkout@v3

            - name: メインブランチへ60日間コミットがないと、スケジュールされたワークフローが停止するのを防止
              # https://docs.github.com/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
              uses: gautamkrishnar/keepalive-workflow@790c7f09285a59b09bb578c85e271c6ff2af97c4 #v1.1.0

            - name: レジストリのキャッシュを展開
              uses: actions/checkout@v3
              with:
                path: ./.vpm/registry/
                ref: registry
              continue-on-error: true

            - uses: actions/setup-node@v3
              with:
                node-version: '18'

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - run: npm --prefix ./.vpm/ ci
            - run: npm --prefix ./.vpm/ run build
              env:
                TAG_NAME: ${{ github.event.release.tag_name }}

            - name: リリースページへ添付
              uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
              with:
                files: ./.vpm/packages/*.zip

            - name: レジストリのキャッシュを保存
              uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: registry
                publish_dir: ./.vpm/registry/
                force_orphan: true

            - name: GitHub Pages用のデータをアップロード
              uses: actions/upload-pages-artifact@v1
              with:
                path: ./.vpm/registry/

    deploy:
        needs: build

        timeout-minutes: 1
        permissions:
            pages: write
            id-token: write
        runs-on: ubuntu-22.04
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
